import type { CourseSource } from "../schema";

/**
 * Courses whose curriculum is designed but whose lessons are not yet written.
 *
 * These are seeded deliberately, and seeded as `published: false`. The roadmap
 * needs to show the complete sixteen-level path or it misrepresents the scope
 * of the platform — but a learner clicking one must land on an honest "being
 * written, here is the outline" page rather than an empty shell dressed up as a
 * lesson. The UI never counts a planned course toward progress, never lets one
 * be marked complete, and labels every entry point.
 */
export const plannedCourses: CourseSource[] = [
  {
    slug: "cpp-for-robotics",
    track: "programming",
    title: "C++ for Robotics",
    subtitle: "The language most production robot code is written in",
    description:
      "Once Python has taught you programming, C++ teaches you what the machine is actually doing. Covers the subset that robotics uses heavily — references, RAII, smart pointers, templates and the real-time constraints that rule out dynamic allocation in a control loop.",
    difficulty: "INTERMEDIATE",
    tags: ["c++", "programming", "real-time"],
    prerequisites: ["python-for-robotics"],
    skills: ["programming"],
    planned: true,
    outline: [
      "From Python to C++: types, compilation and the build step",
      "References, pointers and ownership",
      "RAII and smart pointers",
      "Classes, headers and the compilation model",
      "The STL containers robotics actually uses",
      "Templates and generic code, in moderation",
      "Why a real-time loop must not allocate",
      "CMake and colcon for ROS 2 packages",
      "Writing a ROS 2 node in C++",
    ],
    modules: [],
  },
  {
    slug: "linux-and-tooling",
    track: "programming",
    title: "Linux & Developer Tooling",
    subtitle: "The shell, the filesystem and git — prerequisites for ROS",
    description:
      "ROS runs on Linux, and every ROS tutorial assumes shell fluency it never teaches. This course closes that gap: navigating the filesystem, permissions, processes, environment variables, SSH into a robot, and enough git to collaborate safely.",
    difficulty: "BEGINNER",
    tags: ["linux", "bash", "git", "tooling"],
    prerequisites: [],
    skills: ["programming"],
    planned: true,
    outline: [
      "The filesystem and moving around it",
      "Files, permissions and ownership",
      "Processes, signals and killing a stuck node",
      "Environment variables and why sourcing setup.bash matters",
      "Pipes, redirection and filtering logs",
      "SSH, scp and working on a headless robot",
      "Writing a useful bash script",
      "Git: commit, branch, merge, and undoing mistakes",
    ],
    modules: [],
  },
  {
    slug: "actuators-and-motors",
    track: "sensors-actuators",
    title: "Actuators & Motors",
    subtitle: "Choosing, sizing and closing the loop on the things that move",
    description:
      "DC, servo, stepper and BLDC motors compared honestly, plus linear, pneumatic and hydraulic actuators. Focuses on the calculation that matters most and is most often skipped: sizing a motor from the torque, speed and duty cycle the task actually demands.",
    difficulty: "INTERMEDIATE",
    tags: ["motors", "actuators", "sizing"],
    prerequisites: ["electronics-foundations"],
    skills: ["actuation"],
    planned: true,
    outline: [
      "Torque, speed and the motor curve",
      "Brushed DC motors and H-bridge control",
      "Hobby servos: what is inside and what they hide",
      "Stepper motors, microstepping and lost steps",
      "BLDC motors and field-oriented control",
      "Gearboxes: ratio, backlash and reflected inertia",
      "Sizing a motor from the load — the full worked calculation",
      "Linear actuators, pneumatics and hydraulics",
      "Closing the loop: encoder feedback on a real motor",
    ],
    modules: [],
  },
  {
    slug: "robot-dynamics",
    track: "control",
    title: "Robot Dynamics",
    subtitle: "Forces, torques and why a fast robot is a different problem",
    description:
      "Kinematics ignores mass. Dynamics does not. Covers inertia, gravity and friction at the joint, the Lagrangian formulation, and the feedforward terms that let a robot move quickly without the controller fighting its own arm.",
    difficulty: "ADVANCED",
    tags: ["dynamics", "control", "physics"],
    prerequisites: ["control-systems", "forward-kinematics"],
    skills: ["control-systems"],
    planned: true,
    outline: [
      "Mass, force and torque at a joint",
      "Inertia and why it changes with configuration",
      "Gravity compensation, and what it fixes",
      "Friction models and their limits",
      "The Lagrangian formulation",
      "The manipulator equation, term by term",
      "Computed-torque control",
      "Feedforward versus feedback, and how they combine",
    ],
    modules: [],
  },
  {
    slug: "slam-and-navigation",
    track: "mobile-robotics",
    title: "SLAM & Autonomous Navigation",
    subtitle: "Mapping, localising and getting there without hitting anything",
    description:
      "The full autonomy stack for a mobile robot: occupancy grids, scan matching, particle-filter localisation, graph-based SLAM with loop closure, global and local planners, and the recovery behaviours that decide whether a robot is deployable.",
    difficulty: "ADVANCED",
    tags: ["SLAM", "navigation", "planning"],
    prerequisites: ["mobile-robot-foundations", "ros2-foundations"],
    skills: ["navigation"],
    planned: true,
    outline: [
      "Occupancy grids and log-odds updating",
      "Scan matching and ICP",
      "Monte Carlo localisation with a particle filter",
      "Graph SLAM and loop closure",
      "Dijkstra and A* for global planning",
      "Local planners: DWA and TEB",
      "Costmaps, inflation and footprints",
      "Recovery behaviours and stuck detection",
      "Nav2: configuring it and reading its behaviour tree",
    ],
    modules: [],
  },
  {
    slug: "ros2-advanced",
    track: "ros2",
    title: "ROS 2 in Depth",
    subtitle: "TF2, URDF, launch files, ros2_control and MoveIt 2",
    description:
      "Everything beyond nodes and topics. Building a robot description, publishing a correct transform tree, writing launch files that configure a whole system, integrating hardware through ros2_control, and planning arm motion with MoveIt 2.",
    difficulty: "ADVANCED",
    tags: ["ROS 2", "TF2", "URDF", "MoveIt"],
    prerequisites: ["ros2-foundations"],
    skills: ["ros2"],
    planned: true,
    outline: [
      "Services and actions, written properly",
      "Parameters, YAML and runtime reconfiguration",
      "TF2: broadcasting, listening and debugging a broken tree",
      "URDF and xacro: describing a robot",
      "RViz2: visualising and diagnosing",
      "Launch files and composable nodes",
      "ros2_control: hardware interfaces and controllers",
      "Gazebo integration and simulated sensors",
      "MoveIt 2: planning, execution and collision objects",
      "Recording and replaying with rosbag2",
    ],
    modules: [],
  },
  {
    slug: "ml-for-robotics",
    track: "ai-ml",
    title: "Machine Learning for Robotics",
    subtitle: "Learned perception and learned control, framed by what the robot does next",
    description:
      "Machine learning taught from the robot's perspective. Supervised learning for perception, CNNs and object detection, the deployment realities of running a model on a robot, and reinforcement learning for policies that classical control struggles with.",
    difficulty: "ADVANCED",
    tags: ["machine learning", "deep learning", "reinforcement learning"],
    prerequisites: ["computer-vision-foundations"],
    skills: ["machine-learning"],
    planned: true,
    outline: [
      "What learning buys, and when classical methods are better",
      "Supervised learning and the training loop",
      "Neural networks from first principles",
      "CNNs and why they suit images",
      "Object detection: YOLO-family architectures",
      "Datasets, labelling and the sim-to-real gap",
      "Deploying a model on a robot: latency, quantisation, hardware",
      "Reinforcement learning: states, actions, rewards",
      "Reward shaping and why it goes wrong",
      "Imitation learning and learning from demonstration",
    ],
    modules: [],
  },
  {
    slug: "industrial-robot-cells",
    track: "industrial",
    title: "Industrial Robot Cells",
    subtitle: "Safety, PLCs and integration — how production robots actually get deployed",
    description:
      "The professional track. Risk assessment and the safety standards that govern it, e-stops and safety-rated stops, light curtains and scanners, PLC integration over digital I/O and fieldbus, and the application patterns that make up most installed robots.",
    difficulty: "PROFESSIONAL",
    tags: ["industrial", "safety", "PLC", "integration"],
    prerequisites: ["industrial-manipulators"],
    skills: ["industrial-integration"],
    planned: true,
    outline: [
      "Anatomy of a robot cell",
      "Risk assessment: ISO 12100, ISO 10218 and ISO/TS 15066",
      "Emergency stops, categories 0 and 1, and safe stops",
      "Light curtains, scanners, safety planes and muting",
      "Performance levels and safety-rated controllers",
      "Digital I/O handshakes between robot and PLC",
      "Fieldbus: EtherNet/IP, PROFINET and Modbus",
      "Machine tending and part presence detection",
      "Palletising: patterns, slip sheets and layer logic",
      "Vision-guided placement in a production cell",
      "Robotic welding: process, fixturing and seam tracking",
      "Commissioning, acceptance testing and handover",
    ],
    modules: [],
  },
  {
    slug: "estimation-and-slam",
    track: "advanced",
    title: "Estimation, Fusion & Planning",
    subtitle: "Kalman filters, particle filters and sampling-based planners",
    description:
      "The mathematics behind modern autonomy. Bayesian estimation from first principles, the Kalman filter and its non-linear variants, particle filters, multi-sensor fusion, and sampling-based planners for high-dimensional configuration spaces.",
    difficulty: "PROFESSIONAL",
    tags: ["estimation", "Kalman", "planning", "SLAM"],
    prerequisites: ["slam-and-navigation", "math-for-robotics"],
    skills: ["advanced-robotics"],
    planned: true,
    outline: [
      "Uncertainty, Gaussians and Bayes' rule",
      "The Kalman filter, derived",
      "Extended and Unscented Kalman filters",
      "Particle filters and resampling",
      "Multi-sensor fusion and covariance tuning",
      "Factor graphs and pose-graph optimisation",
      "RRT, RRT* and probabilistic roadmaps",
      "Trajectory optimisation and time parameterisation",
      "Visual servoing: position-based and image-based",
      "Force control: impedance and admittance",
      "Multi-robot coordination and task allocation",
    ],
    modules: [],
  },
  {
    slug: "capstone-systems",
    track: "capstones",
    title: "Capstone Systems",
    subtitle: "Complete robots, designed and defended end to end",
    description:
      "Guided full-system builds that combine perception, planning, control and integration. Each capstone is scoped like a real engineering project: requirements, architecture, implementation, test plan, failure analysis and documentation you could take to an interview.",
    difficulty: "PROFESSIONAL",
    tags: ["capstone", "systems", "integration"],
    prerequisites: ["estimation-and-slam", "industrial-robot-cells"],
    skills: ["advanced-robotics"],
    planned: true,
    outline: [
      "Turning a vague brief into engineering requirements",
      "System architecture and interface definition",
      "Autonomous warehouse robot: the full stack",
      "Vision-guided pick-and-place cell",
      "Autonomous mobile manipulator",
      "Digital twin of an industrial cell",
      "Test plans and acceptance criteria",
      "Failure mode analysis",
      "Documenting a system so someone else can maintain it",
    ],
    modules: [],
  },
];
