import type { AchievementSource, SkillSource } from "./schema";

/**
 * The skill tree is a DAG, not a list: computer vision and navigation both
 * depend on ROS 2 and then converge again at AI. `tier` is the row a node is
 * drawn on and `parents` are the incoming edges; the layout component derives
 * everything else, so adding a skill never means editing coordinates.
 */
export const skills: SkillSource[] = [
  {
    slug: "robotics-literacy",
    name: "Robotics Literacy",
    description:
      "Identify robot types, name their subsystems, and read a robot specification sheet without help.",
    category: "foundation",
    tier: 0,
    courses: ["intro-to-robotics", "robot-anatomy"],
  },
  {
    slug: "programming",
    name: "Programming",
    description: "Write, structure and debug Python and C++ programs for robot control.",
    category: "programming",
    tier: 1,
    parents: ["robotics-literacy"],
    courses: ["python-for-robotics"],
  },
  {
    slug: "electronics",
    name: "Electronics",
    description: "Analyse circuits, drive motors safely and budget power for a mobile robot.",
    category: "electronics",
    tier: 1,
    parents: ["robotics-literacy"],
    courses: ["electronics-foundations"],
  },
  {
    slug: "robot-math",
    name: "Robot Mathematics",
    description: "Use trigonometry, vectors and matrices fluently in a robotics context.",
    category: "math",
    tier: 1,
    parents: ["robotics-literacy"],
    courses: ["math-for-robotics"],
  },
  {
    slug: "sensing",
    name: "Sensing",
    description: "Select sensors, read their datasheets critically and handle their noise.",
    category: "perception",
    tier: 2,
    parents: ["electronics", "programming"],
    courses: ["sensors-deep-dive"],
  },
  {
    slug: "actuation",
    name: "Actuation",
    description: "Size motors from torque and speed requirements and close the loop on them.",
    category: "electronics",
    tier: 2,
    parents: ["electronics", "robot-math"],
    courses: ["actuators-and-motors"],
  },
  {
    slug: "control-systems",
    name: "Control Systems",
    description: "Design and tune feedback controllers, and diagnose them from a step response.",
    category: "control",
    tier: 3,
    parents: ["sensing", "actuation"],
    courses: ["control-systems"],
  },
  {
    slug: "kinematics",
    name: "Kinematics",
    description: "Move fluently between joint space and Cartesian space in both directions.",
    category: "math",
    tier: 3,
    parents: ["robot-math", "actuation"],
    courses: ["coordinate-frames", "forward-kinematics", "inverse-kinematics"],
  },
  {
    slug: "mobile-robots",
    name: "Mobile Robotics",
    description: "Model wheeled robots, integrate odometry and plan collision-free paths.",
    category: "integration",
    tier: 4,
    parents: ["control-systems", "kinematics"],
    courses: ["mobile-robot-foundations"],
  },
  {
    slug: "manipulation",
    name: "Manipulation",
    description: "Program industrial arms, configure frames and select end-of-arm tooling.",
    category: "integration",
    tier: 4,
    parents: ["kinematics", "control-systems"],
    courses: ["industrial-manipulators"],
  },
  {
    slug: "ros2",
    name: "ROS 2",
    description: "Build, launch, introspect and debug distributed ROS 2 systems.",
    category: "integration",
    tier: 5,
    parents: ["mobile-robots", "manipulation", "programming"],
    courses: ["ros2-foundations"],
  },
  {
    slug: "computer-vision",
    name: "Computer Vision",
    description: "Turn camera images into object positions a robot can act on.",
    category: "perception",
    tier: 6,
    parents: ["ros2", "sensing"],
    courses: ["computer-vision-foundations"],
  },
  {
    slug: "navigation",
    name: "Navigation",
    description: "Localise, map and navigate autonomously in an unknown environment.",
    category: "integration",
    tier: 6,
    parents: ["ros2", "mobile-robots"],
    courses: ["slam-and-navigation"],
  },
  {
    slug: "machine-learning",
    name: "Machine Learning",
    description: "Train and deploy models inside a robot's perception and decision loop.",
    category: "perception",
    tier: 7,
    parents: ["computer-vision"],
    courses: ["ml-for-robotics"],
  },
  {
    slug: "industrial-integration",
    name: "Industrial Integration",
    description: "Design safe, PLC-integrated production cells around a robot.",
    category: "integration",
    tier: 7,
    parents: ["manipulation", "navigation"],
    courses: ["industrial-robot-cells"],
  },
  {
    slug: "advanced-robotics",
    name: "Advanced Robotics",
    description:
      "Combine estimation, planning and learning into complete autonomous systems.",
    category: "integration",
    tier: 8,
    parents: ["machine-learning", "navigation", "industrial-integration"],
    courses: ["estimation-and-slam"],
  },
];

export const achievements: AchievementSource[] = [
  {
    slug: "first-lesson",
    name: "Powered On",
    description: "Complete your first lesson.",
    icon: "power",
    tier: "bronze",
    criteriaKind: "LESSON_COUNT",
    threshold: 1,
  },
  {
    slug: "robotics-beginner",
    name: "Robotics Beginner",
    description: "Finish the Introduction to Robotics course.",
    icon: "compass",
    tier: "bronze",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "intro-to-robotics",
  },
  {
    slug: "ten-lessons",
    name: "Getting Traction",
    description: "Complete ten lessons.",
    icon: "steps",
    tier: "bronze",
    criteriaKind: "LESSON_COUNT",
    threshold: 10,
  },
  {
    slug: "python-for-robotics",
    name: "Python for Robotics",
    description: "Finish the Python for Robotics course.",
    icon: "code",
    tier: "silver",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "python-for-robotics",
  },
  {
    slug: "electronics-explorer",
    name: "Electronics Explorer",
    description: "Finish the Electronics Foundations course.",
    icon: "circuit",
    tier: "silver",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "electronics-foundations",
  },
  {
    slug: "sensor-specialist",
    name: "Sensor Specialist",
    description: "Finish the Sensors Deep Dive course.",
    icon: "wave",
    tier: "silver",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "sensors-deep-dive",
  },
  {
    slug: "kinematics-specialist",
    name: "Kinematics Specialist",
    description: "Finish both the forward and inverse kinematics courses.",
    icon: "axes",
    tier: "gold",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "inverse-kinematics",
  },
  {
    slug: "control-engineer",
    name: "Control Engineer",
    description: "Finish the Control Systems course.",
    icon: "gauge",
    tier: "gold",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "control-systems",
  },
  {
    slug: "ros2-developer",
    name: "ROS 2 Developer",
    description: "Finish the ROS 2 Foundations course.",
    icon: "nodes",
    tier: "gold",
    criteriaKind: "COURSE_COMPLETE",
    criteriaRef: "ros2-foundations",
  },
  {
    slug: "first-build",
    name: "First Build",
    description: "Mark your first project complete.",
    icon: "wrench",
    tier: "bronze",
    criteriaKind: "PROJECT_COUNT",
    threshold: 1,
  },
  {
    slug: "builder",
    name: "Builder",
    description: "Complete five projects.",
    icon: "wrench",
    tier: "silver",
    criteriaKind: "PROJECT_COUNT",
    threshold: 5,
  },
  {
    slug: "perfect-quiz",
    name: "Clean Signal",
    description: "Score 100% on any quiz.",
    icon: "target",
    tier: "silver",
    criteriaKind: "QUIZ_SCORE",
    threshold: 100,
  },
  {
    slug: "streak-7",
    name: "Seven-Day Duty Cycle",
    description: "Study seven days in a row.",
    icon: "flame",
    tier: "silver",
    criteriaKind: "STREAK",
    threshold: 7,
  },
  {
    slug: "streak-30",
    name: "Continuous Operation",
    description: "Study thirty days in a row.",
    icon: "flame",
    tier: "gold",
    criteriaKind: "STREAK",
    threshold: 30,
  },
];
